on:
    push:
        branches:
            - dev
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: DevelopmentBuild
jobs:
    buildmac:
        name: Unix
        runs-on: ubuntu-latest
        steps:
            - name: Show Environment
              run: set | grep GIT
            - name: Setup Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.10.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -A
            - name: Dev Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 automatic_release_tag: "development"
                 prerelease: true
                 title: "Development Build"
                 files: release/*
            - name: Push Docker Image
              run: |
                cd $GITHUB_WORKSPACE
                docker login 
                bash compile.sh -P
    buildwindows:
        name: Windows
        needs: buildmac
        runs-on: windows-latest
        steps:
            - name: Setup Python environment
              uses: actions/setup-python@v4
              with:
                python-version: 3.10.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -setupenv
            - name: Build project
              shell: powershell
              run: |
                cd $env:GITHUB_WORKSPACE
                .\compile.ps1 -all -everything
            - name: Dev Release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: latest
                overwrite: true
                file_glob: true
