on:
    push:
        tags:
            - "v3*"
        paths-ignore:
        - README.md
        - CHANGELOG.md
        - .grenrc.yml

name: ReleaseBuild
jobs:
        steps:
            - name: Show Environment
              run: set | grep GIT
            - name: Docker Login
              run: |
                docker login -u ${{ secrets.HUB_USER }} -p ${{ secrets.HUB_PASSWD }}
            - name: Setup Python environment
              uses: actions/setup-python@v2
              with:
                python-version: 3.9.*
            - name: Checkout code
              uses: actions/checkout@master
            - name: Setup Environment
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -S
            - name: Show DockerDef
              run: |
                cd $GITHUB_WORKSPACE
                cat .dockerdef
            - name: Build project
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -A
            - name: Upload Production Release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: release/*
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
            - name: Publish Docker Image
              run: |
                cd $GITHUB_WORKSPACE
                bash compile.sh -P
