# Generated by Django 2.2.1 on 2019-06-25 00:22

import core.DurationField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190605_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmassstart',
            name='adjustment_time',
            field=core.DurationField.DurationField(blank=True, default=None, null=True, verbose_name='Adjustment Time'),
        ),
        migrations.AlterField(
            model_name='resultmassstart',
            name='finish_time',
            field=core.DurationField.DurationField(blank=True, default=None, null=True, verbose_name='Finish Time'),
        ),
        migrations.AlterField(
            model_name='resulttt',
            name='adjustment_time',
            field=core.DurationField.DurationField(blank=True, default=None, null=True, verbose_name='Adjustment Time'),
        ),
        migrations.AlterField(
            model_name='resulttt',
            name='finish_time',
            field=core.DurationField.DurationField(blank=True, default=None, null=True, verbose_name='Finish Time'),
        ),
    ]
