# Generated by Django 2.2.1 on 2019-06-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190624_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategorymassstart',
            name='in_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category', verbose_name='In Category'),
        ),
        migrations.AddField(
            model_name='customcategorytt',
            name='in_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category', verbose_name='In Category'),
        ),
    ]
