# Generated by Django 2.2.1 on 2019-07-11 01:24

import core.DurationField
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190625_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavett',
            name='fastest_participants_start_gap',
            field=core.DurationField.DurationField(blank=True, default=core.models.duration_field_2m, null=True, verbose_name='Fastest Participants Start Gap'),
        ),
        migrations.AlterField(
            model_name='wavett',
            name='gap_before_wave',
            field=core.DurationField.DurationField(blank=True, default=core.models.duration_field_5m, null=True, verbose_name='Gap Before Wave'),
        ),
        migrations.AlterField(
            model_name='wavett',
            name='regular_start_gap',
            field=core.DurationField.DurationField(blank=True, default=core.models.duration_field_1m, null=True, verbose_name='Regular Start Gap'),
        ),
    ]
