# Generated by Django 2.2.1 on 2019-07-22 12:59

import core.DurationField
import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190710_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='start_offset',
            field=core.DurationField.DurationField(blank=True, default=core.models.duration_field_0, null=True, verbose_name='Start Offset'),
        ),
    ]
