# Generated by Django 2.2.1 on 2019-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_series_custom_category_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default='', max_length=32, verbose_name='Code'),
        ),
    ]
