# Generated by Django 2.2.9 on 2020-05-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190920_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'ordering': ['sequence'], 'verbose_name': 'CategoryGroup', 'verbose_name_plural': 'CategoryGroups'},
        ),
        migrations.AlterModelOptions(
            name='customcategorymassstart',
            options={'ordering': ['sequence'], 'verbose_name': 'CustomCategoryMassStart', 'verbose_name_plural': 'CustomCategoriesMassStart'},
        ),
        migrations.AlterModelOptions(
            name='customcategorytt',
            options={'ordering': ['sequence'], 'verbose_name': 'CustomCategoryTT', 'verbose_name_plural': 'CustomCategoriesTT'},
        ),
        migrations.AlterModelOptions(
            name='seriespointsstructure',
            options={'ordering': ['sequence'], 'verbose_name': 'PointsStructure', 'verbose_name_plural': 'PointsStructures'},
        ),
        migrations.AlterModelOptions(
            name='seriesupgradecategory',
            options={'ordering': ['sequence'], 'verbose_name': 'SeriesUpgradeCategory', 'verbose_name_plural': 'SeriesUpgradeCategories'},
        ),
        migrations.AlterModelOptions(
            name='seriesupgradeprogression',
            options={'ordering': ['sequence'], 'verbose_name': 'SeriesUpgradeProgression', 'verbose_name_plural': 'SeriesUpgradeProgressions'},
        ),
    ]
