# Generated by Django 2.2.9 on 2020-05-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200521_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='date_Md',
            field=models.CharField(choices=[('M d', 'd M (Month, day)'), ('d M', 'd M (day, Month)')], default='M d', max_length=24, verbose_name='Month Day Format'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='date_short',
            field=models.CharField(choices=[('Y-m-d', 'Y-m-d (ISO)'), ('d-m-Y', 'd-m-Y (UK)'), ('m-d-Y', 'm-d-Y USA)')], default='Y-m-d', max_length=24, verbose_name='Date Short Format'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='time_hhmmss',
            field=models.CharField(choices=[('H:i:s', 'H:i:s (ISO)'), ('h:i:s P', 'h:i:s P (NA)')], default='H:i:s', max_length=24, verbose_name='Time Short Format'),
        ),
    ]
