# Generated by Django 3.2 on 2021-05-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210501_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultmassstart',
            name='wave_gap',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='resulttt',
            name='wave_gap',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
