# Generated by Django 3.2 on 2021-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210501_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='bib',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Bib'),
        ),
    ]
