# Generated by Django 3.2 on 2021-07-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210505_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseholder',
            name='uci_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, verbose_name='UCI ID'),
        ),
    ]
