# Generated by Django 3.2 on 2021-07-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_licenseholder_uci_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavett',
            name='sequence_option',
            field=models.PositiveSmallIntegerField(choices=[('Increasing', ((0, 'Est. Speed - Increasing'), (1, 'Youngest to Oldest'), (2, 'Bib - Increasing'))), ('Decreasing', ((6, 'Est. Speed - Decreasing'), (3, 'Oldest to Youngest'), (4, 'Bib - Decreasing'))), ('Bib Time Multiple', ((7, 'Bib x 60s'), (8, 'Bib x 30s'))), ('Series', ((5, 'Series Rank'),))], default=0, help_text='Criteria used to order participants in the wave', verbose_name='Sequence Option'),
        ),
    ]
