# Generated by Django 3.2.6 on 2021-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_competition_google_maps_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='google_maps_api_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Google Maps API Key'),
        ),
    ]
