# Generated by Django 4.0.1 on 2022-06-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_competition_google_maps_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='use_sftp',
            field=models.BooleanField(default=False, verbose_name='Use SFTP'),
        ),
    ]
