# Generated by Django 4.1.6 on 2023-02-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_competition_use_sftp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='tag2',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name='Tag2'),
        ),
    ]
