# Generated by Django 4.2 on 2023-05-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_participant_tag_alter_participant_tag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossMgrPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_index=True, max_length=32, verbose_name='Password')),
                ('description', models.CharField(blank=True, default='', max_length=80, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'CrossMgrPassword',
                'verbose_name_plural': 'CrossMgrPasswords',
                'ordering': ['password'],
            },
        ),
        migrations.AlterField(
            model_name='eventmassstart',
            name='optional',
            field=models.BooleanField(default=False, help_text='Allows Participants to choose to enter the Event.  Otherwise the Event is included automatically for all participants in the Event categories.', verbose_name='Optional'),
        ),
        migrations.AlterField(
            model_name='eventtt',
            name='optional',
            field=models.BooleanField(default=False, help_text='Allows Participants to choose to enter the Event.  Otherwise the Event is included automatically for all participants in the Event categories.', verbose_name='Optional'),
        ),
        migrations.CreateModel(
            name='CrossMgrLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Upload')], default=0, verbose_name='Action')),
                ('user', models.CharField(max_length=32, verbose_name='User')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('event_mass_start', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventmassstart', verbose_name='Event Mass Start')),
                ('event_tt', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.eventtt', verbose_name='Event TT')),
            ],
            options={
                'verbose_name': 'CrossMgrLog',
                'verbose_name_plural': 'CrossMgrLogs',
                'ordering': ['timestamp'],
            },
        ),
    ]
