# Generated by Django 4.2 on 2023-05-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_crossmgrpassword_alter_eventmassstart_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossmgrlog',
            name='password',
            field=models.CharField(default='', max_length=32, verbose_name='Password'),
        ),
    ]
