# Generated by Django 4.2 on 2023-05-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_crossmgrlog_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=32, verbose_name='Title')),
                ('description', models.CharField(blank=True, default='', max_length=80, verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['title'],
            },
        ),
    ]
