# Generated by Django 4.2 on 2023-05-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_primemassstart_effort_alter_primett_effort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primemassstart',
            old_name='sponser',
            new_name='sponsor',
        ),
        migrations.RenameField(
            model_name='primett',
            old_name='sponser',
            new_name='sponsor',
        ),
    ]
