# Generated by Django 4.2 on 2023-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_sponser_primemassstart_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, default='', help_text='URL link followed when the viewer clicks on the image', verbose_name='URL'),
        ),
    ]
