# Generated by Django 4.2 on 2023-06-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=160, verbose_name='Description')),
                ('lat_lon_elevation', models.JSONField(editable=False, verbose_name='LatLonElevation')),
                ('is_loop', models.BooleanField(default=True, verbose_name='Is Loop')),
                ('meters', models.FloatField(default=0.0, editable=False, verbose_name='Meters')),
                ('lat_start', models.FloatField(default=0.0, editable=False, verbose_name='LatStart')),
                ('lon_start', models.FloatField(default=0.0, editable=False, verbose_name='LonStart')),
                ('lat_min', models.FloatField(default=0.0, editable=False, verbose_name='LatMin')),
                ('lat_max', models.FloatField(default=0.0, editable=False, verbose_name='LatMax')),
                ('lon_min', models.FloatField(default=0.0, editable=False, verbose_name='LonMin')),
                ('lon_max', models.FloatField(default=0.0, editable=False, verbose_name='LonMax')),
                ('ele_min', models.FloatField(default=0.0, editable=False, verbose_name='EleMin')),
                ('ele_max', models.FloatField(default=0.0, editable=False, verbose_name='EleMax')),
            ],
            options={
                'verbose_name': 'GPX Course',
                'verbose_name_plural': 'GPX Corses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='gpx_course_default',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course Default'),
        ),
        migrations.AddField(
            model_name='eventmassstart',
            name='gpx_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course'),
        ),
        migrations.AddField(
            model_name='eventtt',
            name='gpx_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course'),
        ),
    ]
