# Generated by Django 4.2 on 2023-07-01 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_gpxcourse_competition_gpx_course_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='gpx_course_default',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course Default'),
        ),
        migrations.AlterField(
            model_name='eventmassstart',
            name='gpx_course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course'),
        ),
        migrations.AlterField(
            model_name='eventtt',
            name='gpx_course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gpxcourse', verbose_name='GPX Course'),
        ),
    ]
