# Generated by Django 5.1.1 on 2026-06-16 00:08

import django.db.models.deletion
from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename__7ead293751ac7bbc_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCIRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_id', models.CharField(db_index=True, max_length=11, verbose_name='UCI ID')),
                ('display_name', models.CharField(max_length=128, verbose_name='Display Name')),
                ('team_name', models.CharField(max_length=128, verbose_name='Team Name')),
                ('team_code', models.CharField(max_length=3, verbose_name='Team Code')),
                ('nation_name', models.CharField(max_length=3, verbose_name='Nation Name')),
                ('nation_full_name', models.CharField(max_length=64, verbose_name='Nation Name')),
                ('country_iso2', models.CharField(max_length=2, verbose_name='Country Iso')),
                ('rank', models.FloatField(verbose_name='Rank')),
                ('points', models.FloatField(verbose_name='Points')),
                ('computation_date', models.DateTimeField(verbose_name='Computation Timestamp')),
            ],
            options={
                'verbose_name': 'UCIRank',
                'verbose_name_plural': 'UCIRanks',
                'ordering': ['uci_id'],
            },
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_7fd2125bb4dd353e',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_24d442ccf97b6560',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_1a869c45c49e87f7',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_171956b74b9a836e',
        ),
        migrations.AddField(
            model_name='participant',
            name='series_tank',
            field=models.FloatField(default=None, null=True, verbose_name='Series Rank'),
        ),
        migrations.AddField(
            model_name='participant',
            name='uci_rank',
            field=models.FloatField(default=None, null=True, verbose_name='UCI Rank'),
        ),
        migrations.AddField(
            model_name='ucirank',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition', verbose_name='Competition'),
        ),
        migrations.AddConstraint(
            model_name='ucirank',
            constraint=models.UniqueConstraint(fields=('uci_id',), name='unique uci_id'),
        ),
    ]
