# Generated by Django 5.1.1 on 2026-06-25 15:34

from django.db import migrations

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_ucirank_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_1a2a33c669f73bae',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_2530f831d172985f',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_29c0f86c80fd2b8d',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_7b33d4eb6e993ee8',
        ),
    ]
