# Generated by Django 5.1.1 on 2026-06-25 15:52

from django.db import migrations

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename__1a2a33c669f73bae_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='series_tank',
            new_name='series_rank',
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_39b92ab012ba084a',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_48d6c7ccb06b6201',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_1261995cade0ffeb',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_cd04ef9ff6f196f',
        ),
    ]
