# Generated by Django 5.1.1 on 2026-06-26 05:41

from django.db import migrations

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_series_tank_participant_series_rank_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_419f1d8a11326986',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_557cd22d51594514',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_42fbd9abfd58969b',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_5dca79a66eb1c60a',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='series_rank',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='uci_rank',
        ),
    ]
