# Generated by Django 5.1.1 on 2026-06-27 17:35

import django.db.models.deletion
from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename__3dc4dd3e6acab355_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='MySeries', max_length=128, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('match_key', models.PositiveSmallIntegerField(choices=[(0, 'UCI ID'), (1, 'License Code')], default=0, verbose_name='Match Key')),
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci_id', models.CharField(default=None, max_length=11, null=True, verbose_name='UCI ID')),
                ('license_code', models.CharField(default=None, max_length=32, null=True, verbose_name='License Code')),
                ('rank', models.PositiveIntegerField(verbose_name='Rank')),
                ('points', models.FloatField(default=None, null=True, verbose_name='Points')),
            ],
            options={
                'verbose_name': 'RankingEntry',
                'verbose_name_plural': 'RankingEntries',
                'ordering': ['uci_id', 'license_code'],
            },
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_79c5db74bdc76a51',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_55c199409ee07a5d',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_139b6650742c2414',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_6093c6ff1be2a12e',
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_1_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_2_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_3_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_4_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_1_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_2_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_3_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_4_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Use UCI Rank'), (1, 'Use Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='ucirank',
            name='rank',
            field=models.PositiveIntegerField(verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='ranking',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.competition', verbose_name='Competition'),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ranking', verbose_name='Ranking'),
        ),
    ]
