# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20160726_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='server_print_tag_cmd',
            field=models.CharField(default=b'lpr "$1"', max_length=160, verbose_name='Cmd used to print Bib Tag (parameter is the PDF file)'),
        ),
    ]
