# Generated by Django 5.1.1 on 2026-07-01 21:35

import django.db.models.deletion
from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_ranking_rankingentry_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_57f7cc45c3c5a599',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_1e87607eeaba1ebf',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_537193e89c91716b',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_4262638e3d3d228d',
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='sort_1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='sort_2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='sort_3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='sort_4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_1_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_2_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_3_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_4_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='name',
            field=models.CharField(default='MyRanking', max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_1_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_2_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_3_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='ranking_4_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
    ]
