# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-24 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20161102_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberset',
            name='range_str',
            field=models.CharField(default=b'', max_length=120, verbose_name='Ranges', blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='numbersetentry',
            unique_together=set([]),
        ),
    ]
