# Generated by Django 5.1.1 on 2026-07-09 19:41

import django.db.models.deletion
from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename__57f7cc45c3c5a599_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_b235fc61bfc32b0',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_6c9e30f6d8c94c95',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_173e39b10b8468a5',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_11c2d1fa14f4e8c6',
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AlterField(
            model_name='categorynumbers',
            name='ranking_4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
    ]
