# Generated by Django 5.1.1 on 2026-07-20 00:57

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename__b235fc61bfc32b0_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_1f50c32216f1aa84',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_5d27719b9deccb9a',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_376d66f04a8ac465',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_c0d2bd336be194',
        ),
        migrations.AddField(
            model_name='category',
            name='aliases',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Aliases'),
        ),
    ]
