# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', 'init_nation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='bibs_label_print',
            field=models.BooleanField(default=False, help_text='2 bibs on 2 labels', verbose_name='Bibs Label Print'),
        ),
        migrations.AddField(
            model_name='competition',
            name='bibs_laser_print',
            field=models.BooleanField(default=False, help_text='2 bibs on one page', verbose_name='Bibs Laser Print'),
        ),
        migrations.AddField(
            model_name='competition',
            name='frame_label_print',
            field=models.BooleanField(default=False, help_text='2 frame numbers on 2 labels', verbose_name='Frame Label Print'),
        ),
        migrations.AddField(
            model_name='competition',
            name='shoulders_label_print',
            field=models.BooleanField(default=False, help_text='2 numbers on 2 labels', verbose_name='Shoulders Label Print'),
        ),
    ]
