# Generated by Django 5.1.1 on 2026-07-21 23:26

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename__1f50c32216f1aa84_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ucirank',
            name='unique uci_id',
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_b8e79858f43b5f3',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_23f08fce5362d878',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_3e4b1021f59db8ed',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_3fa7e241af9e9b09',
        ),
        migrations.AlterField(
            model_name='category',
            name='aliases',
            field=models.CharField(blank=True, default='', help_text="Semi-colon (;) separated list of alternate names.  To use regex's, surround the element with slashes (eg /Elite [MH]/ or /Elite [WF]/)", max_length=160, verbose_name='Aliases'),
        ),
    ]
