# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20161207_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='bib_label_print',
            field=models.BooleanField(default=False, help_text='2 bibs on 2 labels', verbose_name='1 Bib Label Print'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='bibs_label_print',
            field=models.BooleanField(default=False, help_text='2 bibs on 2 labels', verbose_name='2 Bibs Label Print'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='bibs_laser_print',
            field=models.BooleanField(default=False, help_text='2 bibs on one page', verbose_name='2 Bibs Laser Print'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='frame_label_print',
            field=models.BooleanField(default=False, help_text='2 frame numbers on 2 labels', verbose_name='2 Frame Label Print'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='shoulders_label_print',
            field=models.BooleanField(default=False, help_text='2 numbers on 2 labels', verbose_name='2 Shoulders Label Print'),
        ),
    ]
