# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-17 01:20
from __future__ import unicode_literals

import core.DurationField
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20161208_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTimeMassStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_time', core.DurationField.DurationField(verbose_name='Race Time')),
            ],
            options={
                'verbose_name': 'RaceTimeMassStart',
                'verbose_name_plural': 'RaceTimesMassStart',
            },
        ),
        migrations.CreateModel(
            name='RaceTimeTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_time', core.DurationField.DurationField(verbose_name='Race Time')),
            ],
            options={
                'verbose_name': 'RaceTimeTT',
                'verbose_name_plural': 'RaceTimesTT',
            },
        ),
        migrations.CreateModel(
            name='ResultMassStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='Status')),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=None, null=True, verbose_name='Rank')),
                ('finish_time', core.DurationField.DurationField(blank=True, null=True, verbose_name='Finish Time')),
                ('adjustment_time', core.DurationField.DurationField(blank=True, default=0.0, verbose_name='Adjustment Time')),
                ('adjustment_note', models.CharField(default=b'', max_length=128, verbose_name='Adjustment Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventMassStart')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
            options={
                'verbose_name': 'ResultMassStart',
                'verbose_name_plural': 'ResultsMassStart',
            },
        ),
        migrations.CreateModel(
            name='ResultTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0, verbose_name='Status')),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=None, null=True, verbose_name='Rank')),
                ('finish_time', core.DurationField.DurationField(blank=True, null=True, verbose_name='Finish Time')),
                ('adjustment_time', core.DurationField.DurationField(blank=True, default=0.0, verbose_name='Adjustment Time')),
                ('adjustment_note', models.CharField(default=b'', max_length=128, verbose_name='Adjustment Note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventTT')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Participant')),
            ],
            options={
                'verbose_name': 'ResultTT',
                'verbose_name_plural': 'ResultsTT',
            },
        ),
        migrations.AddField(
            model_name='racetimett',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ResultTT', verbose_name='ResultTT'),
        ),
        migrations.AddField(
            model_name='racetimemassstart',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ResultMassStart', verbose_name='ResultMassStart'),
        ),
        migrations.AlterUniqueTogether(
            name='resulttt',
            unique_together=set([('participant', 'event')]),
        ),
        migrations.AlterUniqueTogether(
            name='resultmassstart',
            unique_together=set([('participant', 'event')]),
        ),
    ]
