# Generated by Django 5.1.1 on 2026-07-22 02:20

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_ucirank_unique_uci_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingentry',
            options={'ordering': ['uci_id', 'license_code', 'last_name', 'first_name'], 'verbose_name': 'RankingEntry', 'verbose_name_plural': 'RankingEntries'},
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_32a53af89bc9f819',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_1fd07e581ce60121',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_195c60efc32c80c4',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_344d9ffd6b405cb5',
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='match_key',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI ID'), (1, 'License Code'), (2, 'First Last Name')], default=0, verbose_name='Match Key'),
        ),
    ]
