# Generated by Django 5.1.1 on 2026-07-26 13:50

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_rankingentry_options_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_50e0855c355cea74',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_632d1e306410d3a5',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_6efd22dd88fcf71d',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_317b23d9aafb9598',
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='reverse',
            field=models.BooleanField(default=False, verbose_name='Reverse'),
        ),
    ]
