# Generated by Django 5.1.1 on 2026-07-28 14:07

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename__50e0855c355cea74_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_2511c54349fcb214',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_31859f7cd285e16d',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_52be5696e5a2ef13',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_6c909cc8559d1aa4',
        ),
        migrations.AddField(
            model_name='ranking',
            name='import_timestamp',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last Imported'),
        ),
        migrations.AlterField(
            model_name='wavett',
            name='sequence_option',
            field=models.PositiveSmallIntegerField(choices=[('Increasing', [(0, 'Est. Speed - Increasing'), (1, 'Youngest to Oldest'), (2, 'Bib - Increasing'), (9, 'Rank - highest rank goes last')]), ('Decreasing', [(6, 'Est. Speed - Decreasing'), (3, 'Oldest to Youngest'), (4, 'Bib - Decreasing'), (10, 'Rank - highest rank goes first')]), ('Bib Time Multiple', [(7, 'Bib x 60s'), (8, 'Bib x 30s')]), ('Series', [(5, 'Series Rank')])], default=0, help_text='Criteria used to order participants in the wave', verbose_name='Sequence Option'),
        ),
    ]
