# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20161227_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='cloud_server_url',
            field=models.CharField(default=b'', max_length=160, blank=True, verbose_name='Cloud Server Url'),
        ),
    ]
