# Generated by Django 5.1.1 on 2026-07-28 14:19

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_rename__2511c54349fcb214_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_5ac0be9b856f3b14',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_86a8b91b4f97056',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_1f64b70a6bed49f4',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_4f0f14e718f1effb',
        ),
        migrations.AlterField(
            model_name='ranking',
            name='import_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Imported'),
        ),
    ]
