# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20170107_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='must_have_completed',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 or more Events'), (1, '1 or more Events'), (2, '2 or more Events'), (3, '3 or more Events'), (4, '4 or more Events'), (5, '5 or more Events'), (6, '6 or more Events'), (7, '7 or more Events'), (8, '8 or more Events'), (9, '9 or more Events'), (10, '10 or more Events'), (11, '11 or more Events'), (12, '12 or more Events'), (13, '13 or more Events'), (14, '14 or more Events'), (15, '15 or more Events'), (16, '16 or more Events'), (17, '17 or more Events'), (18, '18 or more Events'), (19, '19 or more Events'), (20, '20 or more Events'), (21, '21 or more Events'), (22, '22 or more Events'), (23, '23 or more Events'), (24, '24 or more Events'), (25, '25 or more Events'), (26, '26 or more Events'), (27, '27 or more Events'), (28, '28 or more Events'), (29, '29 or more Events'), (30, '30 or more Events')], default=0, verbose_name='Must have completed'),
        ),
    ]
