# Generated by Django 5.1.1 on 2026-08-04 21:25

import django.db.models.deletion
from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename__5ac0be9b856f3b14_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingentry',
            options={'ordering': ['uci_id', 'license_code', 'last_name', 'first_name', 'bib'], 'verbose_name': 'RankingEntry', 'verbose_name_plural': 'RankingEntries'},
        ),
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_78b6b3caf3ced9cc',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_69bed847173fb5c8',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_134cd602b173d0fd',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_641f834c5009a836',
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='categorynumbers',
            name='ranking_5_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AddField(
            model_name='rankingentry',
            name='bib',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Bib'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ranking'),
        ),
        migrations.AddField(
            model_name='wave',
            name='ranking_5_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI'), (1, 'Ranking')], default=1),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='match_key',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UCI ID'), (1, 'License Code'), (2, 'First Last Name'), (3, 'Bib')], default=0, verbose_name='Match Key'),
        ),
    ]
