# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20170107_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='consider_most_events_completed',
            field=models.BooleanField(default=False, verbose_name='Consider Most Events Completed'),
        ),
        migrations.AddField(
            model_name='series',
            name='show_last_to_first',
            field=models.BooleanField(default=True, verbose_name='Show Events Last to First'),
        ),
    ]
