# Generated by Django 5.1.1 on 2026-08-05 17:00

import core.DurationField
from django.db import migrations

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_rankingentry_options_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_29c5cf854c2d969e',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_6c84795c37948293',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_53302aa3cc1f2577',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_446c469b3b4100d5',
        ),
        migrations.AddField(
            model_name='entrytt',
            name='gap_time_calculated',
            field=core.DurationField.DurationField(blank=True, null=True, verbose_name='Calculated Gap Time'),
        ),
        migrations.AddField(
            model_name='entrytt',
            name='gap_time_custom',
            field=core.DurationField.DurationField(blank=True, null=True, verbose_name='Custom Gap Time'),
        ),
    ]
