# Generated by Django 5.1.1 on 2026-08-06 14:14

import core.DurationField
from django.db import migrations

# Ignore exceptions from RenameIndex which can occure if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rename__29c5cf854c2d969e_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_43102ff44f17ded7',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_19641b90b05e8f29',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_54e38f80b7f0bb24',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_505130d7eb930374',
        ),
        migrations.AddField(
            model_name='entrytt',
            name='start_time_custom',
            field=core.DurationField.DurationField(blank=True, null=True, verbose_name='Custom Start Time'),
        ),
    ]
