# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-11 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20170107_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriespointsstructure',
            options={'verbose_name': 'PointsStructure', 'verbose_name_plural': 'PointsStructures'},
        ),
        migrations.AddField(
            model_name='series',
            name='callup_max',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Callup Maximum'),
        ),
        migrations.AddField(
            model_name='series',
            name='randomize_if_no_results',
            field=models.BooleanField(default=False, verbose_name='Randomize callups if no results'),
        ),
    ]
