# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-26 14:44
from __future__ import unicode_literals

import core.DurationField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20170111_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmassstart',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='resultmassstart',
            name='time_bonus',
            field=core.DurationField.DurationField(blank=True, null=True, verbose_name='Time Bonus'),
        ),
        migrations.AddField(
            model_name='resulttt',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='resulttt',
            name='time_bonus',
            field=core.DurationField.DurationField(blank=True, null=True, verbose_name='Time Bonus'),
        ),
        migrations.AddField(
            model_name='series',
            name='consider_primes',
            field=models.BooleanField(default=True, verbose_name='Consider Points or Time Primes'),
        ),
    ]
