# Generated by Django 5.1.1 on 2026-09-11 16:35

from django.db import migrations, models

# Ignore exceptions from RenameIndex which can occur if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_rename__43102ff44f17ded7_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_7cf6bea8c3558e81',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_224ad4c696af43ad',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_5f4a2045909358',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_4141f0744ca19e4',
        ),
        migrations.AddField(
            model_name='wave',
            name='cycle_category_callups',
            field=models.BooleanField(default=False, help_text='Cycle callups if multiple categories are in the Wave.  For example, A.1, B.1, C.1, A.2, B.2, A3.', verbose_name='Cycle Category Callups'),
        ),
    ]
