# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-03 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20170126_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='bib_label_print',
            field=models.BooleanField(default=False, help_text='1 bib on 1 label', verbose_name='1 Bib Label Print'),
        ),
    ]
