# Generated by Django 5.1.1 on 2026-09-18 15:41

import core.DurationField
import datetime
from django.db import migrations

# Ignore exceptions from RenameIndex which can occur if the old indexes don't exist.
from core.IgnoreException import IgnoreExceptionSubclass
RenameIndexIgnoreException = IgnoreExceptionSubclass( migrations.RenameIndex )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename__7cf6bea8c3558e81_core_entryt_event_i_f9f4e7_idx_and_more'),
    ]

    operations = [
        RenameIndexIgnoreException(
            model_name='entrytt',
            new_name='core_entryt_event_i_f9f4e7_idx',
            old_name='_20dcddcfdac3f721',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_36c115_idx',
            old_name='_5e7d431951a269e5',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_c665bb_idx',
            old_name='_1f75cdc11d331f4f',
        ),
        RenameIndexIgnoreException(
            model_name='participantoption',
            new_name='core_partic_competi_21c187_idx',
            old_name='_200a23cb8bec2f8a',
        ),
        migrations.AddField(
            model_name='eventmassstart',
            name='min_possible_lap_time',
            field=core.DurationField.DurationField(default=15.0, verbose_name='Min Possible Lap Time'),
        ),
        migrations.AddField(
            model_name='eventtt',
            name='min_possible_lap_time',
            field=core.DurationField.DurationField(default=15.0, verbose_name='Min Possible Lap Time'),
        ),
    ]
