# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20170202_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='tag_bits',
            field=models.PositiveSmallIntegerField(choices=[(64, b'64'), (96, b'96')], default=96, help_text='EPC Bits available if generating Universally Unique tags.', verbose_name='EPC Bits per Tag'),
        ),
        migrations.AddField(
            model_name='systeminfo',
            name='tag_creation',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Universally Unique'), (1, 'From Database ID'), (2, 'From License Code')], default=0, help_text='Specify how to create RFID tags.', verbose_name='Tag Creation'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='tag_from_license_id',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=0, help_text='Identifier if generating tags from License Code.', verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='tag_template',
            field=models.CharField(help_text='Template if generating tags from Database ID.', max_length=24, verbose_name='Tag Template'),
        ),
    ]
