# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-24 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20170221_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='license_holder_unique_by_license_code',
            field=models.BooleanField(default=True, help_text='If True, License Holders will be Merged assuming that License Codes are permanent and unique.  Otherwise, ignore and attempt to match by Last, First, Gender and DOB', verbose_name='License Codes Permanent and Unique'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='tag_from_license_id',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=0, help_text='Identifier for generating tags from License Code.', verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Team Code'),
        ),
    ]
