# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20170403_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategoryMassStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(blank=True, default=32767, verbose_name='Sequence')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('range_str', models.CharField(blank=True, default=b'', help_text='e.g. 1-199, -35-45', max_length=128, verbose_name='Bib Ranges')),
                ('nation_code_str', models.CharField(blank=True, default=b'', help_text='3-letter ISO Country Codes, comma separated', max_length=128, verbose_name='Nation Codes')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'All')], default=2, verbose_name='Gender')),
                ('date_of_birth_minimum', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth Minimum')),
                ('date_of_birth_maximum', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth Maximum')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventMassStart', verbose_name='EventMassSart')),
            ],
            options={
                'verbose_name': 'CustomCategoryMassStart',
                'verbose_name_plural': 'CustomCategoriesMassStart',
            },
        ),
        migrations.CreateModel(
            name='CustomCategoryTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(blank=True, default=32767, verbose_name='Sequence')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('range_str', models.CharField(blank=True, default=b'', help_text='e.g. 1-199, -35-45', max_length=128, verbose_name='Bib Ranges')),
                ('nation_code_str', models.CharField(blank=True, default=b'', help_text='3-letter ISO Country Codes, comma separated', max_length=128, verbose_name='Nation Codes')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Men'), (1, 'Women'), (2, 'All')], default=2, verbose_name='Gender')),
                ('date_of_birth_minimum', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth Minimum')),
                ('date_of_birth_maximum', models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth Maximum')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EventTT', verbose_name='EventTT')),
            ],
            options={
                'verbose_name': 'CustomCategoryTT',
                'verbose_name_plural': 'CustomCategoriesTT',
            },
        ),
    ]
