# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20170506_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcategorytt',
            name='nation_code_str',
            field=models.CharField(blank=True, default=b'', help_text='3-letter IOC Country Codes, comma separated', max_length=128, verbose_name='Nation Codes'),
        ),
    ]
