# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20170506_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='systeminfo',
            name='tag_all_hex',
            field=models.BooleanField(default=True, help_text='Set to True if all tags characters are in [0-9A-F]', verbose_name='RFID Tag all Hex'),
        ),
    ]
