# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_systeminfo_tag_all_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcategorymassstart',
            name='competitive_age_maximum',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Competitive Age Max'),
        ),
        migrations.AddField(
            model_name='customcategorymassstart',
            name='competitive_age_minimum',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Competitive Age Min'),
        ),
        migrations.AddField(
            model_name='customcategorytt',
            name='competitive_age_maximum',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Competitive Age Max'),
        ),
        migrations.AddField(
            model_name='customcategorytt',
            name='competitive_age_minimum',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Competitive Age Min'),
        ),
    ]
