# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20170601_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='frame_label_print_1',
            field=models.BooleanField(default=False, help_text='1 frame number on 1 label', verbose_name='1 Frame Label Print'),
        ),
    ]
