# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-10 03:09
from __future__ import unicode_literals

import core.DurationField
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20170609_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtt',
            name='group_size',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of starters without a Group Size Gap.  The Group Size Gap will be inserted between riders of Group Size (if non-zero).', verbose_name='Group Size'),
        ),
        migrations.AddField(
            model_name='eventtt',
            name='group_size_gap',
            field=core.DurationField.DurationField(default=5*60, verbose_name='Group Size Gap'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='long_name',
            field=models.CharField(blank=True, default=b'', max_length=80, verbose_name='Long Name (Title)'),
        ),
    ]
