# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-19 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20170609_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmassstart',
            name='relegated',
            field=models.BooleanField(default=False, verbose_name='Relegated'),
        ),
        migrations.AddField(
            model_name='resulttt',
            name='relegated',
            field=models.BooleanField(default=False, verbose_name='Relegated'),
        ),
    ]
