# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20170619_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=64, verbose_name='Alias')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team')),
            ],
            options={
                'ordering': ['team__search_text'],
                'verbose_name': 'Team Alias',
                'verbose_name_plural': 'Team Aliases',
            },
        ),
    ]
