# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20171013_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategoryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_check_required', models.BooleanField(default=False, verbose_name='License Check Required')),
                ('note', models.CharField(blank=True, default=b'', max_length=160, verbose_name='Note')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
            options={
                'verbose_name': 'CompetitionCategoryOption',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='license_checked',
            field=models.BooleanField(default=False, verbose_name='License Checked'),
        ),
        migrations.AlterUniqueTogether(
            name='competitioncategoryoption',
            unique_together=set([('competition', 'category')]),
        ),
    ]
