# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20171013_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='license_requirement',
            field=models.CharField(blank=True, default=b'', max_length=32, verbose_name='License Requirement'),
        ),
    ]
