# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-10 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_category_license_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionCategoryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_check_required', models.BooleanField(default=False, verbose_name='License Check Required')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Competition')),
            ],
            options={
                'verbose_name': 'CompetitionCategoryOption',
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitioncategoryoption',
            unique_together=set([('competition', 'category')]),
        ),
    ]
