# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-12-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_auto_20171211_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='license_check_note',
            field=models.CharField(blank=True, default=b'', max_length=240, verbose_name='License Check Note'),
        ),
    ]
