# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_competition_license_check_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='report_label_license_check',
            field=models.ForeignKey(blank=True, help_text='Previous Competitions considered for License Check must have this label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.ReportLabel', verbose_name='Report Label License Check'),
        ),
    ]
