# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_competition_report_label_license_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseCheckState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LicenseHolder')),
                ('report_label_license_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ReportLabel')),
            ],
        ),
    ]
