# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-12 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20180324_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='rfid_server_port',
            field=models.PositiveIntegerField(default=50111, verbose_name='RFID Reader Server Port'),
        ),
    ]
