# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-12 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20180512_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseholder',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default=b'', max_length=64, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='licenseholder',
            name='phone',
            field=models.CharField(blank=True, default=b'', max_length=64, verbose_name='Phone'),
        ),
    ]
