# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20180512_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseholder',
            name='emergency_medical',
            field=models.CharField(blank=True, default=b'', help_text='eg. diabetic, drug alergy, etc.', max_length=128, verbose_name='Medical Alert'),
        ),
    ]
