# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20180512_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='contact_phone',
            field=models.CharField(blank=True, default=b'', max_length=64, verbose_name='Contact Phone'),
        ),
    ]
