# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20180512_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensecheckstate',
            name='discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Discipline'),
        ),
    ]
