# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-21 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20180524_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbersetentry',
            name='date_issued',
            field=models.DateField(db_index=True, default=None, null=True, verbose_name='Date Issued'),
        ),
    ]
