# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20180725_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseholder',
            name='ineligible_on_date_time',
            field=models.DateTimeField(blank=True, default=None, help_text='Date/Time when the License Holder starts to be ineligible.  Defaults to the next day.  If blank, the License Holder will be ineligible immediately.  ', null=True, verbose_name='Ineligible Starting at'),
        ),
    ]
